server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        #user microservice ip
        - id: voterModule
          uri: http://18.231.148.123
          predicates:
            - Path=/voter/**
        #user microservice ip
        - id: userModule
          uri: http://18.231.148.123
          predicates:
            - Path=/user/**
        #user microservice ip
        - id: managerModule
          uri: http://18.231.148.123
          predicates:
            - Path=/manager/**
        #political partu microservice ip
        - id: partyModule
          uri: http://18.231.31.135
          predicates:
            - Path=/party/**
        #political partu microservice ip
        - id: candidateModule
          uri: http://18.231.31.135
          predicates:
            - Path=/candidate/**
        #dependency microservice ip
        - id: s3Module
          uri: http://18.228.206.60
          predicates:
            - Path=/s3/**
