server:
  port: 8040
  error:
    include-message: always
    include-binding-errors: always

spring:
  cloud:
    gateway:
      routes:
        - id: party-service
          uri: http://177.71.157.239
          predicates:
            - Path=/party/**
          filters:
            - StripPrefix=1
      
